version: '3'
services:
  webapp:
    build: .
    image: xinxin8/web-docker-webapp:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=hospitaldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
  db:
    image: xinxin8/web-docker-db-with-data:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hospitaldb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: